# Generated by Django 5.1.7 on 2025-03-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('tech', 'Technical Document'), ('news', 'Newspaper/Article'), ('blog', 'Blog Post'), ('other', 'Other')], max_length=10)),
                ('file', models.FileField(upload_to='documents/')),
                ('text_content', models.TextField(blank=True, null=True)),
                ('task', models.CharField(choices=[('summarize', 'Summarize'), ('reformat', 'Reformat'), ('grammar', 'Grammar Check'), ('all', 'All Tasks')], default='summarize', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
